[aws]
disabled = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[battery.display]
threshold = 10
style = "bold red"

[character]
symbol = "âœ"
error_symbol = "âœ—"
use_symbol_for_status = true

[cmd_duration]
min_time = 2
format = "took [$duration]($style) "

[conda]
symbol = "env "

[directory]
fish_style_pwd_dir_length = 1

[username]
show_always = true
